PROVIDERS = {
    "opencode": {
        "name": "OpenCode Zen",
        "base_url": "https://opencode.ai/zen/v1",
        "allow_anonymous": True,
        "models": [
            "deepseek-v4-flash",
            "claude-sonnet-4-20250514",
            "claude-haiku-3-5-20241022",
            "gemini-2.5-pro-exp-03-25",
            "gemini-2.5-flash-preview-05-15",
            "gemini-2.0-flash-exp",
            "gpt-5.5",
            "gpt-5.5-pro",
            "gpt-5.4-mini",
            "gpt-5.4-nano",
            "gpt-5.3-codex",
            "gpt-5.2",
            "gpt-5.1-codex",
            "gpt-5.1",
            "gpt-5",
            "gpt-5-codex",
            "gpt-5-nano",
            "llama-3.3-70b-specdec",
            "mistral-medium-3.5-128b",
            "qwen3.6-plus",
            "qwen3.5-plus",
            "minimax-m2.7",
            "minimax-m2.5",
            "glm-5.1",
            "kimi-k2.6",
            "kimi-k2.5",
        ],
        "free_models": [
            "deepseek-v4-flash-free",
            "mimo-v2.5-free",
            "qwen3.6-plus-free",
            "minimax-m3-free",
            "nemotron-3-super-free",
            "gemini-2.0-flash-exp",
        ],
        "rate_limit": {
            "min_request_interval": 0.5,
            "max_retries": 3,
            "base_backoff": 1.0,
        },
        "docs_url": "https://opencode.ai/zen",
        "api_key_hint": "occ_... or sk-...",
    },
    "deepseek": {
        "name": "DeepSeek",
        "base_url": "https://api.deepseek.com",
        "models": [
            "deepseek-v4-flash",
            "deepseek-v4-pro",
        ],
        "rate_limit": {
            "min_request_interval": 1.0,
            "max_retries": 3,
            "base_backoff": 1.0,
        },
        "docs_url": "https://platform.deepseek.com/api_keys",
        "api_key_hint": "sk-...",
    },
    "openrouter": {
        "name": "OpenRouter",
        "base_url": "https://openrouter.ai/api/v1",
        "models": [
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-pro",
            "google/gemini-3.5-flash",
            "google/gemini-3.1-flash-lite",
            "google/gemini-2.5-flash",
            "openai/gpt-5.5",
            "openai/gpt-5.5-pro",
            "openai/gpt-5.4-mini",
            "openai/gpt-chat-latest",
            "openai/gpt-mini-latest",
            "anthropic/claude-opus-4.8",
            "anthropic/claude-sonnet-4.6",
            "anthropic/claude-haiku-3.5",
            "qwen/qwen3.7-max",
            "qwen/qwen3.5-plus",
            "meta-llama/llama-3.3-70b-instruct",
            "mistralai/mistral-medium-3.5",
            "minimax/minimax-m3",
            "xai/grok-4.3",
            "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
            "stepfun/step-3.7-flash",
        ],
        "rate_limit": {
            "min_request_interval": 0.5,
            "max_retries": 3,
            "base_backoff": 1.0,
        },
        "docs_url": "https://openrouter.ai/keys",
        "api_key_hint": "sk-or-v1-...",
    },
    "nvidia": {
        "name": "NVIDIA NIM",
        "base_url": "https://integrate.api.nvidia.com/v1",
        "models": [
            "nvidia/llama-3.3-nemotron-super-49b-v1",
            "nvidia/nemotron-3-super-120b-a12b",
            "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
            "meta/llama-3.2-90b-vision-instruct",
            "deepseek/deepseek-v4-flash",
            "deepseek/deepseek-v4-pro",
            "mistralai/mistral-medium-3.5-128b",
            "google/gemma-4-31b-it",
            "qwen/qwen3.5-122b-a10b",
            "minimax/minimax-m2.7",
            "stepfun/step-3.5-flash",
            "z-ai/glm-5.1",
        ],
        "rate_limit": {
            "min_request_interval": 2.0,
            "max_retries": 5,
            "base_backoff": 2.0,
        },
        "docs_url": "https://build.nvidia.com",
        "api_key_hint": "nvapi-...",
    },
    "gemini": {
        "name": "Google Gemini",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai/",
        "models": [
            "gemini-3.5-flash",
            "gemini-3.1-flash-lite",
            "gemini-2.5-pro",
            "gemini-2.5-flash",
            "gemini-2.5-flash-lite",
        ],
        "rate_limit": {
            "min_request_interval": 0.5,
            "max_retries": 3,
            "base_backoff": 1.0,
        },
        "docs_url": "https://aistudio.google.com/apikey",
        "api_key_hint": "AIza...",
    },
    "custom": {
        "name": "Custom (OpenAI-Compatible)",
        "base_url": "",
        "models": [],
        "rate_limit": {
            "min_request_interval": 1.0,
            "max_retries": 3,
            "base_backoff": 1.0,
        },
        "docs_url": "",
        "api_key_hint": "sk-...",
    },
}

DEFAULT_SETTINGS: dict[str, any] = {
    "provider": "openrouter",
    "api_base_url": PROVIDERS["openrouter"]["base_url"],
    "api_model": PROVIDERS["openrouter"]["models"][0],
    "api_key": "",
    "api_timeout": 120,
    "theme": "dark",
    "font_size": 12,
    "window_width": 1200,
    "window_height": 800,
    "max_file_size_mb": 10,
    "max_attachments": 10,
    "allowed_extensions": [
        ".py", ".js", ".ts", ".tsx", ".jsx",
        ".java", ".go", ".rs", ".cpp", ".c", ".h", ".hpp",
        ".cs", ".php", ".rb", ".swift", ".kt", ".scala",
        ".json", ".yaml", ".yml", ".toml", ".ini", ".xml",
        ".md", ".txt", ".rst", ".html", ".css",
        ".png", ".jpg", ".jpeg", ".gif", ".webp",
    ],
    "check_for_updates": False,
    "send_analytics": False,
    "auto_save_conversations": True,
    # Agent core configuration
    "agent_type": "main",
    "max_iterations": 10,
    "compaction_threshold": 0.8,
    "compaction_max_tokens": 128000,
    "doom_loop_threshold": 3,
    "permission_cache_ttl": 0,
}

AGENT_TYPES: dict[str, dict] = {
    "main": {
        "tools": [
            "web_search", "web_fetch", "terminal",
            "file_read", "file_write", "file_glob", "file_grep",
            "voice",
        ],
        "permission_defaults": {
            "allow_read": True,
            "ask_mutation": True,
            "deny_destructive": True,
        },
    },
    "web": {
        "tools": ["web_search", "web_fetch"],
        "permission_defaults": {
            "allow_read": True,
            "ask_mutation": False,
            "deny_destructive": True,
        },
    },
    "terminal": {
        "tools": ["terminal"],
        "permission_defaults": {
            "allow_read": False,
            "ask_mutation": True,
            "deny_destructive": True,
        },
    },
    "file": {
        "tools": ["file_read", "file_write", "file_glob", "file_grep"],
        "permission_defaults": {
            "allow_read": True,
            "ask_mutation": True,
            "deny_destructive": True,
        },
    },
    "voice": {
        "tools": ["voice"],
        "permission_defaults": {
            "allow_read": True,
            "ask_mutation": False,
            "deny_destructive": True,
        },
    },
}
